{
  "branches": ["main", "fix/build"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/github",
      {
        "assets": [
          {"path": "target/bootstrap.sh", "label": "Bootstrap script"}
        ]
      }
    ]
  ]
}
